name: Build QuickDns

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore QuickDNS.sln

    # Self-contained single file (fat exe, includes runtime + sqlite dll)
    - name: Publish self-contained
      run: dotnet publish QuickDnsConsole/QuickDNSConsole.csproj `
             -c Release -r win-x64 --self-contained true `
             -p:PublishSingleFile=true `
             -p:DebugType=none -p:DebugSymbols=false `
             -p:IncludeNativeLibrariesForSelfExtract=true `
             -o publish/self-contained

    # Framework-dependent (lighter, requires .NET Runtime installed)
    - name: Publish framework-dependent
      run: dotnet publish QuickDnsConsole/QuickDNSConsole.csproj `
             -c Release -r win-x64 --self-contained false `
             -p:PublishSingleFile=true `
             -p:DebugType=none -p:DebugSymbols=false `
             -p:IncludeNativeLibrariesForSelfExtract=false `
             -o publish/framework

    - name: Create/Update Release (Latest)
      uses: softprops/action-gh-release@v1
      with:
        tag_name: latest
        name: "QuickDNS Latest Build"
        body: "Auto-build includes:\n- Self-contained exe (no .NET needed)\n- Framework-dependent exe (lighter, requires .NET 9 runtime)"
        files: |
          publish/self-contained/*
          publish/framework/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
